export const step1Items = [
  {
    title: 'Developers',
    desc: 'Software Engineers, Integration Developers, and DevOps.',
  },
  {
    title: 'Designers',
    desc: 'UI/UX, Branding, and Visual Designers.',
  },
  {
    title: 'Product Managers',
    desc: 'Product Managers, Product Owners, and Business Analysts.',
  },
  {
    title: 'Data Experts',
    desc: 'Data Scientists, Big Data Experts, and Data Analysts.',
  },
  {
    title: 'QA',
    desc: 'Manual, Automation Engineers and Test Analysts.',
  },
];

export const step2Items = [
  {
    title: 'Full-time',
    desc: '40 hrs/week',
    value: 'fulltime',
  },
  {
    title: 'Part-time',
    desc: '20 hrs/week',
    value: 'parttime',
  },
];

export const skills = [
  { id: 1, slug: 'python', name: 'Python' },
  { id: 2, slug: 'ruby', name: 'Ruby' },
  { id: 3, slug: 'nodejs', name: 'Node.js' },
  { id: 4, slug: 'ruby-on-rails', name: 'Ruby on Rails' },
  { id: 5, slug: 'blockchain', name: 'Blockchain' },
  { id: 6, slug: 'javascript-developers', name: 'JavaScript' },
  { id: 7, slug: 'salesforce', name: 'Salesforce' },
  { id: 8, slug: 'magento', name: 'Magento' },
  { id: 9, slug: 'emberjs', name: 'Ember.js' },
  { id: 10, slug: 'react-native', name: 'React Native' },
  { id: 11, slug: 'vuejs', name: 'Vue.js' },
  { id: 12, slug: 'scala', name: 'Scala' },
  { id: 13, slug: 'react', name: 'ReactJS' },
  { id: 14, slug: 'devops', name: 'DevOps' },
  { id: 15, slug: 'drupal', name: 'Drupal' },
  { id: 16, slug: 'angular', name: 'Angular' },
  { id: 17, slug: 'wordpress', name: 'Wordpress' },
  { id: 18, slug: 'haxe', name: 'Haxe' },
  { id: 19, slug: 'php', name: 'PHP' },
  { id: 20, slug: 'aspnet-mvc', name: 'ASP.NET MVC' },
  { id: 21, slug: 'android', name: 'Android' },
  { id: 22, slug: 'backbonejs', name: 'Backbone.js' },
  { id: 23, slug: 'phonegap', name: 'PhoneGap' },
  { id: 24, slug: 'java', name: 'Java' },
  { id: 25, slug: 'ms-sql', name: 'MS SQL' },
  { id: 26, slug: 'amazon-ec2', name: 'Amazon EC2' },
  { id: 27, slug: 'groovy', name: 'Groovy' },
  { id: 28, slug: 'svg', name: 'SVG' },
  { id: 29, slug: 'catalyst', name: 'Catalyst' },
  { id: 30, slug: 'cocoa', name: 'Cocoa' },
  { id: 31, slug: 'objective-c', name: 'Objective C' },
  { id: 32, slug: 'ajax', name: 'AJAX' },
  { id: 33, slug: 'java-ee', name: 'Java EE' },
  { id: 34, slug: 'django', name: 'Django' },
  { id: 35, slug: 'opengl', name: 'OpenGL' },
  { id: 36, slug: 'visual-studio', name: 'Visual Studio' },
  { id: 37, slug: 'google-docs', name: 'Google Docs' },
  { id: 38, slug: 'ractivejs', name: 'Ractive.js' },
  { id: 39, slug: 'd3js', name: 'd3.js' },
  { id: 40, slug: 'apache-cordova', name: 'Apache Cordova' },
  { id: 41, slug: 'sailsjs', name: 'Sails.js' },
  { id: 42, slug: 'ebay-api', name: 'ebay API' },
  { id: 43, slug: 'lamp', name: 'LAMP' },
  { id: 44, slug: 'amazon-s3', name: 'Amazon S3' },
  { id: 45, slug: 'haskell', name: 'Haskell' },
  { id: 46, slug: 'rackspace', name: 'Rackspace' },
  { id: 47, slug: 'aws', name: 'AWS' },
  { id: 48, slug: 'windows-phone', name: 'Windows phone' },
  { id: 49, slug: 'elastic-search', name: 'Elastic search' },
  { id: 50, slug: 'game', name: 'Game' },
  { id: 51, slug: 'front-end', name: 'Front End' },
  { id: 52, slug: 'spring', name: 'Spring' },
  { id: 53, slug: 'kotlin', name: 'Kotlin' },
  { id: 54, slug: 'firebase', name: 'Firebase' },
  { id: 55, slug: 'chatbot', name: 'Chatbot' },
  { id: 56, slug: 'brew', name: 'Brew' },
  { id: 57, slug: 'c', name: 'C#' },
  { id: 58, slug: 'bootstrap', name: 'Bootstrap' },
  { id: 59, slug: 'algorithms', name: 'Algorithms' },
  { id: 60, slug: 'access', name: 'Access' },
  { id: 61, slug: 'adobe', name: 'Adobe' },
  { id: 62, slug: 'umbraco', name: 'Umbraco' },
  { id: 63, slug: 'arduino', name: 'Arduino' },
  { id: 64, slug: 'asterisk', name: 'Asterisk' },
  { id: 65, slug: 'awk', name: 'AWK' },
  { id: 66, slug: 'git', name: 'Git' },
  { id: 67, slug: 'windows-adk', name: 'Windows ADK' },
  { id: 68, slug: 'mac-os', name: 'Mac OS' },
  { id: 69, slug: 'opencv', name: 'OpenCV' },
  { id: 70, slug: 'actionscript', name: 'ActionScript' },
  { id: 71, slug: 'admob', name: 'AdMob' },
  { id: 72, slug: 'adobe-air', name: 'Adobe AIR' },
  { id: 73, slug: 'alfresco', name: 'Alfresco' },
  { id: 74, slug: 'apache-ofbiz', name: 'Apache OFBiz' },
  { id: 75, slug: 'apache-tapestry', name: 'Apache Tapestry' },
  { id: 76, slug: 'apache-wicket', name: 'Apache Wicket' },
  { id: 77, slug: 'oracle-apex', name: 'Oracle APEX' },
  { id: 78, slug: 'appcelerator', name: 'Appcelerator' },
  { id: 79, slug: 'appfuse', name: 'AppFuse' },
  { id: 80, slug: 'arcgis', name: 'ArcGIS' },
  { id: 81, slug: 'arch-linux', name: 'Arch Linux' },
  { id: 82, slug: 'cross-platform', name: 'Cross Platform' },
  { id: 83, slug: 'boonex', name: 'BoonEx' },
  { id: 84, slug: 'microsoft-xna', name: 'Microsoft XNA' },
  { id: 85, slug: 'bottle', name: 'Bottle' },
  { id: 86, slug: 'box', name: 'Box' },
  { id: 87, slug: 'brutos', name: 'Brutos' },
  { id: 88, slug: 'buddypress', name: 'BuddyPress' },
  { id: 89, slug: 'cakephp', name: 'CakePHP' },
  { id: 90, slug: 'carma', name: 'CARMA' },
  { id: 91, slug: 'corona', name: 'Corona' },
  { id: 92, slug: 'chrome-extensions', name: 'Chrome Extensions' },
  { id: 93, slug: 'clarion', name: 'Clarion' },
  { id: 94, slug: 'cms', name: 'CMS' },
  { id: 95, slug: 'cognos', name: 'Cognos' },
  { id: 96, slug: 'crm', name: 'CRM' },
  { id: 97, slug: 'cython', name: 'Cython' },
  { id: 98, slug: 'db2', name: 'DB2' },
  { id: 99, slug: 'devexpress', name: 'DevExpress' },
  { id: 100, slug: 'dotnetnuke', name: 'DotNetNuke' },
];
